server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
            allowCredentials: true
      routes:
        - id: authentication-server
          uri: http://127.0.0.1:8090
          predicates:
            - Path=/authentication-server/**

        - id: main-page-service
          uri: http://127.0.0.1:8091
          predicates:
            - Path=/main-page/**
          filters:
            - AuthenticationFilter

        - id: friends-service
          uri: http://127.0.0.1:8093
          predicates:
            - Path=/friends-service/**
          filters:
            - AuthenticationFilter





#        - id: chat-service
#          uri: http://127.0.0.1:8092
#          predicates:
#            - Path=/chat-api/**
#          filters:
#            - AuthenticationFilter
#
#        - id: chat
#          uri: http://127.0.0.1:8092
#          predicates:
#            - Path=/ws/info/**
#
#        - id: websocket-route
#          uri: ws://127.0.0.1:8092
#          predicates:
#            - Path=/ws/**


#        - id: chat
#          uri: lb://127.0.0.1:8092
#          predicates:
#            - Path=/ws/info/**

#          filters:
#            - name: RewritePath
#              args:
#                regexp: /ws/(?<segment>.*)
#                replacement: /ws/$\{segment}



#          metadata:
#            cors:
#              allowedOrigins: '*'
#              allowedMethods:
#                - GET
#                - POST
#              allowedHeaders: '*'
#              allowCredentials: false
#              maxAge: 30

#  management:
#    endpoint:
#      gateway:
#        enabled: true # default value
#    endpoints:
#      web:
#        exposure:
#          include: gateway

security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

