server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
            allowCredentials: true
      routes:
        - id: main-page-service
          uri: http://127.0.0.1:8091
          predicates:
            - Path=/main-page/**
          filters:
            - AuthenticationFilter

        - id: authentication-server
          uri: http://127.0.0.1:8090
          predicates:
            - Path=/authentication-server/**

        - id: chat-service
          uri: http://127.0.0.1:8092
          predicates:
            - Path=/**
            - Path=/ws/**
          filters:
            - AuthenticationFilter
#          metadata:
#            cors:
#              allowedOrigins: '*'
#              allowedMethods:
#                - GET
#                - POST
#              allowedHeaders: '*'
#              allowCredentials: false
#              maxAge: 30

#  management:
#    endpoint:
#      gateway:
#        enabled: true # default value
#    endpoints:
#      web:
#        exposure:
#          include: gateway

security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

