spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat-service
#  mvc:
#    cors:
#      mappings:
#        /ws/**:
#          allowed-origins: "http://localhost:3000"
#          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
#          allowed-headers: "*"
#          allow-credentials: true
server:
  port: 8092
