spring:
  application:
    name: authentication-server
  data:
    mongodb:
      uri: mongodb://localhost:27017/main-page

server:
  port: 8090


jwt:
  uri: /auth/**
  header: Authorization
  prefix: Bearer
  expiration: 86400
  secret: JwtSecretKey